spring.application.name=tonkatsu-db-backend

spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/trackdb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=${PORT:8080}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://main.d7cgaeiwb3kth.amplifyapp.com}
